// <auto-generated />
using System;
using Cadastro_Pessoas.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Cadastro_Pessoas.Migrations
{
    [DbContext(typeof(dbContext))]
    partial class dbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:Collation", "Latin1_General_CI_AS")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.11")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Cadastro_Pessoas.Models.TbCargo", b =>
                {
                    b.Property<int>("Codigo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Cargo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("NiveldeAcesso")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.HasKey("Codigo");

                    b.ToTable("tbCargo");
                });

            modelBuilder.Entity("Cadastro_Pessoas.Models.TbColaborador", b =>
                {
                    b.Property<int>("Codigo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<byte>("Ativo")
                        .HasColumnType("tinyint");

                    b.Property<int?>("CodigoCargo")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nchar(80)")
                        .IsFixedLength(true);

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nchar(80)")
                        .IsFixedLength(true);

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nchar(20)")
                        .IsFixedLength(true);

                    b.HasKey("Codigo");

                    b.HasIndex("CodigoCargo");

                    b.ToTable("tbColaborador");
                });

            modelBuilder.Entity("Cadastro_Pessoas.Models.TbColaborador", b =>
                {
                    b.HasOne("Cadastro_Pessoas.Models.TbCargo", "CodigoCargoNavigation")
                        .WithMany("TbColaboradors")
                        .HasForeignKey("CodigoCargo")
                        .HasConstraintName("fkCargo");

                    b.Navigation("CodigoCargoNavigation");
                });

            modelBuilder.Entity("Cadastro_Pessoas.Models.TbCargo", b =>
                {
                    b.Navigation("TbColaboradors");
                });
#pragma warning restore 612, 618
        }
    }
}
